#!/bin/sh
set -e
export OPENSSL_CONF=`pwd`/debian/openssl.cnf
cp -a tests "$AUTOPKGTEST_TMP"/
cd "$AUTOPKGTEST_TMP"
for py in $(py3versions -s); do echo "[*] testing $py:"; $py -Wd -m pytest -v -rs 2>&1; done
